### ISSUE TITLE
Node 8.10.0: Error: The module '/home/dietpi/xdk2mam-ruuvitag/xdk2mam-ruuvitag-direct/node_modules/bluetooth-hci-socket/build/Release/binding.node' was compiled against a different Node.js

### ISSUE THREAD

**Issue by antonionardella** [xdk2mam/xdk2mam-ruuvitag#1]
Hello,

tried to start the direct app with node v8.10.0 and I get the following error:
```
xdk2mam-ruuvitag/xdk2mam-ruuvitag-direct$ sudo node app.js 30000
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/dietpi/xdk2mam-ruuvitag/xdk2mam-ruuvitag-direct/node_modules/bluetooth-hci-socket/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/dietpi/xdk2mam-ruuvitag/xdk2mam-ruuvitag-direct/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```

Cheers,
Antonio

**Comment by demichele** [comment]
Hi Antonio, could you complete the Node modules installation without any errors?

**Comment by demichele** [comment]
Finally after some troubleshooting this issue was a mix of: 

- different Node versions on the regular and root user (when doing sudo node app.js 30000) the node version being used was 10. 
- The Raspberry Pi3 not having the BT active. 

We strongly recommend to use the combo **Node 8.10.0 & NPM 5.6.0**. 
Thanks Antonio for always testing our code!!!
